server:
 port: 8080

spring:
  profiles:
    active: google

security:
  oauth2:
    client:
      clientId: 560858891996-l8ngro6pemcnatp2tcj3q490mkf7q9dl.apps.googleusercontent.com
      clientSecret: 5gDfVsl0Kc6v02D1nl9fKwil
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      clientAuthenticationScheme: form
      scope:
        - openid
        - email
        - profile
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
      preferTokenInfo: true